apiVersion: apps/v1
kind: Deployment
metadata:
  name: hub
  labels:
    app: "hub"
spec:
  replicas: 1
  strategy:
    # strategy
    type: RollingUpdate
  selector:
    matchLabels:
      app: "hub"
  template:
    metadata:
      labels:
        app: "hub"
    spec:
      containers:
        - name: jupyter
          imagePullPolicy: Always
          command: ["jupyterhub", "--port", "8888", "--config", "./.init/jupyterhub_config.py"]
          env:
            - name: OAUTH_CALLBACK_URL
              value: "https://jhub.{{ .Values.hub.host }}.myip.cloud.infn.it/hub/oauth_callback"
            - name: OAUTH_ENDPOINT
              value: "{{ .Values.iam.endpoint }}"
            - name: OAUTH_SUB
              value:  "{{ .Values.iam.oauth_sub }}"
            - name: OAUTH_GROUPS
              value:  "{{ .Values.iam.oauth_groups }}"
            - name: ADMIN_OAUTH_GROUPS
              value:  "{{ .Values.iam.oauth_admin_groups }}"
            - name: S3_ENDPOINT
              value: "{{ .Values.s3.endpoint }}"
            - name: S3_BUCKET
              value: "{{ .Values.s3.bucket }}"
            - name: SPAWNED_IMAGE
              value: "{{ .Values.hub.spawned_image }}"
            - name: CVMFS_SNAPSHOTTER
              value: "{{ .Values.hub.cvmfs_snapshotter }}"
          image: "{{ .Values.hub.image }}"
          ports:
          - containerPort: 8888
